### ISSUE TITLE
Crest4 runtime and memory requirement

### ISSUE THREAD

**Issue by rzhan186** [xapple/crest4#1]
Dear CREST developers,

Thank you for developing this tool! I am running a nucleotide file (~12G) against the silvmod128 database using vsearch with about 125G memories. 

However, I received an error message that seemed to indicate there isn’t sufficient memory. 

`slurmstepd: error: Detected 1 oom-kill event(s) in StepId=63476927.batch. Some of your processes may have been killed by the cgroup out-of-memory handle`

Is it possible to estimate the run time and memory requirements given the size of a FASTA file?

Thank you for your help!

**Comment by xapple** [comment]
You can try running the vsearch command separately with this command:

    $ vsearch --usearch_global sequences.fasta -db ~/.crest4/silvamod138/silvamod138.udb -blast6out seq_search.hits -threads 32 -id 0.75 -maxaccepts 100

And you can observe using `top` or `htop` how much memory it consumes.

**Comment by rzhan186** [comment]
Hi @xapple ,

Thank you for your prompt reply! What is the difference between running crest4 and vsearch, does running vsearch separately improve the memory efficiency? 

And once VSEARCH finishes running, how can I determine the OTU table or taxonomic classification from the search_hit file? Can I supply this file to the crest4 program to get the taxonomic classification?

Thanks!

**Comment by lanzen** [comment]
Hi Rui,

The default option of crest4 is to run BLAST. vsearch is an alternative to
this, but both are called from crest4, so neither vsearch or BLAST are
really alternatives to CREST as such. They provide the alignments that
CREST work on to do the lowest common ancestor classification. Both are
supported so you do not have to figure out how to use the output of
vsearch. CREST doest that for you.

Another option is that you divide your FASTA file and run BLAST
sequentially or in paralell on each partition, then concatenate the BLAST
results and run crest4 using option -s and provide the path to the
concatenated BLAST output. The BLAST format should be XML. This is also
useful if you have access to a cluster on which you could run a great
number of BLAST queries in parallel because an input file of 12G will take
quite a long time to align. Are you actually providing a FASTA file with
only rRNA sequences or is this pure metagenome reads or metagenome contigs?
In the later case, I strongly recommend using a faster program like
SortMeRNA or BBDuk to identify all the SSU rRNA sequences before trying to
align them to SilvaMod138PR2. This will remove some 99.8% of the sequences,
speed up the BLAST search, and most likely solve your memory issues.

 If the 12G file instead is from total RNA sequencing, i.e.
non-rRNA-depleted total RNA metatranscriptomics, then you can also do this
to remove LSU rRNA (about 50% of total RNA reads) but another option is to
also use a dedicated rRNA assembly program like MetaRIb:
https://pubmed.ncbi.nlm.nih.gov/32167532/

Cheers,
Anders

**Comment by rzhan186** [comment]
Dear Anders @lanzen ,

Thank you for your clarifications! Before running crest4, I have run SortMeRNA (see code below) on my raw metatranscriptomic sequencing reads to obtain the “aligned sequences”, which I believe are the rRNA sequences. 

```

sortmerna \
--ref smr_v4.3_default_db.fasta \
--reads $input/rna.fastq \
--aligned $output/aligned \
--other $output/unaligned \
--workdir $output \
--fastx \
--threads 32
```

Then I used the aligned sequences (~12G) as input for crest4. 

```
crest4 \
--fasta $input/aligned.fixed.fa \
-o $output/crest4_vsearch \
-a vsearch \
-t 32
```

I’ve come across literature where people have shown that SortMeRNA could discern SSU and LSU rRNA, but I couldn’t find the functionality in the software for doing so, could you tell me how to do that specifically? 

Best,
Rui

**Comment by lanzen** [comment]
Hi,

I think that the ability of SortMeRNA to sort one type of rRNA from another
(SSU v LSU) depends only on the database you use for alignment. If
smr_v4.3_default_db.fasta
contains both LSU and SSU, then so will aligned.fa. If it only contains
SSU, then aligned.fa should also contain only SSU.

Did you verify that aligned.fa is in the right format, i.e. normal
un-aligned FASTA?

Did your FASTQ input contain pair reads? If so, I think you should run
SortMeRNA a bit differently and it would be better to do read pair
overlapping before submitting the sequences to BLAST and CREST.

Anders

**Comment by rzhan186** [comment]
Hi Anders, 

Thanks for the insight. I agree that it’s the database used that matters for distinguishing between different rRNA types, I will contact the SortMeRNA authors for the correct database to use for SSU rRNA. The current database (smr_v4.3_default_db.fasta
) I used seems to contain both SSU and LSU rRNA. Regarding reads overlapping, I have used a software called FLASH to overlap the paired-end RNA reads before running SoftMeRNA, so I think my data are fine in that regard. 

Meanwhile, following the previous thread, VSEARCH finished running after 12 hours with 250G of memory, creating a search.hit file of 56G from the 12G aligned sequencing file. How can I use this search.hit file for classification? Can I provide this file to CREST for the LCA classification? 

 Best,
Rui
