### ISSUE TITLE
Classification thresholds for ranks above phylum level

### ISSUE THREAD

**Issue by naurasd** [xapple/crest4#5]
Hi

in the documentation, it says...

> In addition to the lowest common ancestor classification, a minimum similarity filter is used, based on a set of taxon-specific requirements, by default depending on their taxonomic rank. By default, a sequence must be aligned with at least 99% nucleotide similarity to the best reference sequence in order to be classified to the species rank. For the genus, family, order, class and phylum ranks the respective default cut-offs are 97%, 95%, 90%, 85% and 80%. 

I was wondering how this is handled for reference databases that do not follow these ranks. I have 18S and ITS metabarcoding data sets that were classified using PR2 v.4.14.0 and Unite v7.2, respectively. 

For ITS for example, Unite will output a classification with 9 ranks:

`"Domain","Supergroup","Division/Kingdom","Phylum","Class","Order","Family","Genus","Species"`

Running Crest with the default bit scores and similarity thresholds, I get some OTUs assigned as Fungi at the kingdom level, but unclassified at phylum level. I guess that actually, these are phylum assignments, because I get the following classification for those:

`Cellular organisms;Eukaryota;Opisthokonta;Fungi;Unknown Fungi phylum 1`
`Cellular organisms;Eukaryota;Opisthokonta;Fungi;Unknown Fungi phylum 2`
`Cellular organisms;Eukaryota;Opisthokonta;Fungi;Unknown Fungi phylum 3`
`Cellular organisms;Eukaryota;Opisthokonta;Fungi;Unknown Fungi phylum 4`

So I think in Unite, the reference sequences are deposited as "Unknown Fungi phylum" and this way Crest can make a phylum level assignment. Correct?

For 18S, the taxonomy doesnt really follow those ranks as for ITS. But I also have OTUs that are for example classified at the domain level, but unclassified at the supergroup level, and OTUs that are classified at supergroup level, but unclassified at division/kingdom level.

I for example get some assignments like this:

`Main genome;Eukaryota;Alveolata`

So this is an assignment to supergroup level only. I am not sure if this is due to a sequence deposited in PR2 that has this taxonomy attributed to it, or if Crest only assigns to supergroup level because some threshold is not met. Either way, what similarity threshold is applied for levels above phylum rank? What thresholds were met when an OTU gets assigned to supergroup, but not to kingdom level? Or is it that in this case, the 80% phylum threshold was met, but a lower rank classification couldnt be made, because the deposited sequence in PR2 just didnt have a lower-rank taxonomy attributed to it?

Thanks a lot

Nauras

**Comment by lanzen** [comment]
Hi,

To first answer your question, there is no similarity threshol for ranks above phylum. Also, if you want to see what phylum that it assigns your OTUs to without the similarity cutoff, you simply can unactivate it usign the option -f (or --nofilter). Because I assume that this is a result from CREST v3 and not CREST4 although you have filed the issue here? UNITE was never made available for CREST4 and unfortunately I have stopped maintaining it, but I could try to find time early next year to provide a version for CREST4 based on the latest release. 

The sequences that are assigned to only supergroup and is not called "unknown" something (when not using -u, because then all "unknown" ranks are removed), they result from either (i) a very low percentage similarity and very dispersed matches, (ii) to one or more matches with severely conflicting taxonomy, or (iii) high similarity to a sequence with very little taxonomic resolution (although all reference sequences that did not have at least phylum rank info were removed if I remember it correctly). I have seen this during testing for PR2 since it is not based on a global alignment tree, as opposed to SILVA. Can you send me the OTU sequence so that I can look at it? If it is the later, I should revise the database to remove the problematic reference sequence.

Best,
Anders

**Comment by xapple** [comment]
If this is resolved, I will close this issue. If there are more problems, don't hesitate to reopen.

It seems to me this concerns crest3 and not crest4.
